# Homework 1 - Numpy

For all the questions, print the results with a variable of your choice (e.g., Z)

#### 1. Import the numpy package under the name `np` 

In [1]:
import numpy as np

#### 2. Create a vector with values ranging from 10 to 49 

In [8]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 3. Reverse a vector (first element becomes last) 

In [9]:
v = v[::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 4. Create a 3x3 matrix with values ranging from 0 to 8 

In [10]:
v2 = np.arange(0, 9).reshape(3, 3)
print(v2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 5. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [24]:
v3 = [1, 2, 0, 0, 4, 0]
np.nonzero(v3)

(array([0, 1, 4]),)

#### 6. Create a 3x3 identity matrix 

In [15]:
vi = np.identity(3)
print(vi)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 7. Create a 3x3x3 array with random values 

In [17]:
vr = np.random.random((3, 3, 3))
print(vr)

[[[0.40937466 0.17481833 0.03967453]
  [0.39334547 0.07943152 0.4228318 ]
  [0.32039502 0.70755743 0.35548206]]

 [[0.42102171 0.28423461 0.65848232]
  [0.29503099 0.42929347 0.06351582]
  [0.66253396 0.15206139 0.23263111]]

 [[0.57699447 0.02304744 0.94720231]
  [0.30380563 0.13557125 0.24540559]
  [0.70139483 0.56343293 0.14597469]]]


#### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [21]:
vr2 = np.random.random((10, 10))
print(vr2)
print("Minimum :",vr2.min(),"\n"+"Maximum :",vr2.max())

[[0.99182872 0.72176841 0.05474816 0.79686323 0.32773996 0.90017451
  0.54003702 0.14496788 0.76025926 0.61216205]
 [0.37717726 0.85657329 0.24937107 0.01149052 0.10408999 0.31090902
  0.82534672 0.59797941 0.97326286 0.82862059]
 [0.65252368 0.95565679 0.9066845  0.99535746 0.36796454 0.4111938
  0.4302561  0.29817539 0.40453245 0.47828859]
 [0.49826483 0.20509438 0.79623078 0.47308004 0.7784137  0.85300705
  0.540388   0.82207911 0.43180556 0.54653495]
 [0.50146565 0.43429868 0.99314429 0.06596794 0.33852184 0.32632744
  0.23046165 0.55804466 0.85897452 0.61731313]
 [0.84319787 0.3848168  0.62407935 0.21735583 0.65319745 0.50142083
  0.3986201  0.39955665 0.63493772 0.97350579]
 [0.58687747 0.44284874 0.78913914 0.01278867 0.26149038 0.7543845
  0.18529422 0.15609255 0.37781506 0.58791659]
 [0.84634352 0.1720422  0.01057625 0.49268914 0.53517607 0.7623148
  0.3432877  0.48204993 0.55497625 0.86164955]
 [0.34369311 0.47966317 0.05986196 0.92713692 0.4798477  0.24084855
  0.56161446 0.

#### 9. Create a checkerboard 8x8 matrix using np.array([0,1],[1,0]) and the tile function  

In [22]:
Cb = np.tile(np.array([[0,1], [1, 0]]),(4,4))
print(Cb)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [23]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
AB = np.dot(A, B)
print(A)
print(B)
print(AB)

[[0.58787801 0.15015395 0.37050681]
 [0.40851286 0.57362725 0.02670172]
 [0.34853253 0.98268101 0.63290426]
 [0.24875317 0.03281391 0.88424633]
 [0.56238242 0.71606073 0.74682693]]
[[0.92536878 0.61350385]
 [0.54495639 0.97919484]
 [0.83653218 0.74057151]]
[[0.93577218 0.78208218]
 [0.71296372 0.83209159]
 [1.3874842  1.64477308]
 [0.98777109 0.83958988]
 [1.53537776 1.5992655 ]]


#### 11. Create a 5x5 matrix with row values ranging from 0 to 4 using tile function as follows:


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [27]:
M = np.tile(np.array([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]), (1))
print(M)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 12. Create a 5x5 matrix with row values ranging from 0 to 4 using broadcasting


In [30]:
M = np.zeros((5, 5)) + np.arange(5)
print(M)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 13. Create a random vector of size 10 and sort it 

In [33]:
v = np.random.random(10)
v.sort()
print(v)

[0.11269702 0.18737065 0.22374381 0.29981864 0.40179483 0.42041854
 0.46380338 0.71683827 0.72285456 0.88960696]


#### 14. Subtract the mean of each row

X = np.random.rand(5,10)

In [36]:
X = np.random.rand(5,10)
Xm = X.mean(axis = 0)
print(Xm)

[0.67563006 0.57879986 0.59663563 0.45424776 0.32403861 0.49153159
 0.39159489 0.70458484 0.86752997 0.53630614]


#### 15. Create, 10 by 10 multiplication table from 1 to 10

In [37]:
for i in range(1, 11):
  for j in range(1, 11):
    print(i, "*", j, "=", i*j)

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90
10 * 1 = 10
10 * 2 = 20


#### 16. How to get the diagonal of a dot product? 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [39]:
A = np.random.uniform(0,1,(5,5)) 
B = np.random.uniform(0,1,(5,5))
AB = np.dot(A, B)
print(AB.diagonal())

[0.79233099 0.87662703 1.26460905 1.1545015  0.88954489]


#### 17. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [40]:
v = np.array([1,2,3,4,5])
n = 3
vn = np.zeros(len(v) + (len(v)-1)*(n))
vn[::n+1] = v
print(vn)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 18. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

In [42]:
A = np.random.randint(0,5,(8,3)) 
B = np.random.randint(0,5,(2,2))
New = (A[..., np.newaxis, np.newaxis] == B)
r = (New.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(r)

[0 1 2 3 4 5 6 7]


#### 19. How to swap two rows of an array? Generate an array from 0 to 24, and reshape it 5 by 5 and swap first two rows of the array

In [46]:
arr = np.arange(0, 25).reshape((5, 5))
print(arr)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 20. How to find the most frequent value in an array? 

Z = np.random.randint(0,10,50). hint: np.bincount, np.argmax

In [47]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


#### 21. How to get the n largest values of an array?

start with 
Z = np.arange(10000);
np.random.shuffle(Z)
, Hint: np.argsort

In [48]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 10
print (Z[np.argsort(Z)[-n:]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


#### 22. Given a two dimensional array, how to extract unique rows? 

Hint: np.unique

In [50]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
print(Z[idx])

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]


#### 23. How to compute averages using a sliding window over an array? 

make a function with two arguments, arry and size of the sliding window, def moving_avg(arr, n)


In [60]:
def moving_avg(arr, n):
  for i in range(len(arr)-n+1):
    sum_win = 0
    for j in range(n):
      sum_win += arr[i+j]
    avg_win = sum_win/n
    print("average of window num", i, "is", avg_win)

ar = [2, 5, 2, 1, 3, 5, 8, 6, 23, 1]
n = 3

print("array :", ar)
print("size of the window :", n)
moving_avg(ar, n)

array : [2, 5, 2, 1, 3, 5, 8, 6, 23, 1]
size of the window : 3
average of window num 0 is 3.0
average of window num 1 is 2.6666666666666665
average of window num 2 is 2.0
average of window num 3 is 3.0
average of window num 4 is 5.333333333333333
average of window num 5 is 6.333333333333333
average of window num 6 is 12.333333333333334
average of window num 7 is 10.0


#### 24. Find the indices of elements from 4 by 4 random matrix (0-1) which are larger than 0.5

Print a list of tuples indicating the index for row and column


In [53]:
arr = np.random.random((4,4))
for i in range(4):
  for j in range(4):
    if arr[i, j] > 0.5:
      print(i, j)

0 0
0 1
0 3
1 0
1 3
2 0
2 2
3 0


#### 25. Write a function returning distance between two points

Test the function to check whether function is working correctly
Hint: There are two arguments of function indicating two points

In [56]:
def distance(a, b):
  sum = 0
  for i in range(len(a)):
    sum += (a[i]-b[i])**2
  dis = np.sqrt(sum)
  return dis

A = [1, 2]
B = [3, 4]
print(distance(A, B))

2.8284271247461903
